version: "3"

services:
  redis:
    image: redis

  worker:
    image: ${LAMMPS_MPI_NATIVE_IMAGE}
    entrypoint: /code/experiment-mpi-native/run/lammps.sh
    working_dir: /code/experiment-mpi-native
    privileged: true
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib:/build/faabric/install/lib
      - FUNCTION_STORAGE=local
      - LOG_LEVEL=debug
      - REDIS_STATE_HOST=redis
      - REDIS_QUEUE_HOST=redis
    depends_on:
      - redis

  master:
    image: ${FAABRIC_MPI_NATIVE_IMAGE}
    entrypoint: ['/code/experiment-mpi-native/run/lammps.sh', 'master', '${MPI_WORLD_SIZE}']
    working_dir: /code/faabric
    privileged: true
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib:/build/faabric/install/lib
      - FUNCTION_STORAGE=local
      - LOG_LEVEL=debug
      - REDIS_STATE_HOST=redis
      - REDIS_QUEUE_HOST=redis
    depends_on:
      - redis
      - worker
